### ISSUE TITLE
Clatrix not transposing V* matrix in correctly in SVD return

### ISSUE THREAD

**Issue by mikera** [tel/clatrix#63]
core.matrix API specifics that V* should be the transpose of the V matrix in the SVD decomposition. Clatrix is currently returning the non-transposed V.

See https://github.com/mikera/vectorz-clj/issues/47

**Comment by nblumoe** [comment]
@mikera thanks for raising and fixing this over here.
Should we handle this somewhere upstream, too, until it gets fixed in clatrix?

I currently have pending changes to Incanter with fixed tests. However these tests fail now, when using the clatrix implementation. Of course I could add something to Incanter, but core.matrix would seem to be more appropriate.

More importantly: Can we get this fix merged, please?

**Comment by mikera** [comment]
@nblumoe OK I merged it.... don't seem to have been any objections to this fix.

I can't make official Clatrix releases though

**Comment by tel** [comment]
Do you not have Clojar's access? I can fix that.



—

**Comment by mikera** [comment]
@tel - actually looks like I do have membership of the clatrix group on clojars.... 
a) does that mean I can make a release?
b) Should I? (this isn't my project after all!)

**Comment by tel** [comment]
Ah, great!




I haven’t been an active maintainer for quite some time, so I don’t want to weigh in on decisions like that. I just wanted to make sure there wasn’t any structural reason you couldn’t release :)




Pinging @Quantisan?


—

**Comment by Quantisan** [comment]
Please do @mikera 
Looks to me like you've been the maintainer for this library for a while, so you make the call.

**Comment by tel** [comment]
I'm happy discussing anything necessary for the release as necessary.

**Comment by mikera** [comment]
OK I created a 0.5.0 release - hope that works for everyone!

**Comment by tel** [comment]
Great! Thanks!
